### PR TITLE
Follow upstream

### LINKED ISSUE #3: Update image to follow upstream closer
Uppdatera imagen för Specify7 så att denna ligger nära den officiella Specify-imagen.

### LINKED ISSUE #7: Fix connection to specify6.gnmspecify.se.

### PR DESCRIPTION
**Pull request by mskyttner**
- Updates docs with new URLs/slugs
- Attempts to fix #3 
- Attempts to fix #7

### CODE REVIEW

**Review by chrisIsen — APPROVED** [review]
Seems fine

**Review by chrisIsen — COMMENTED** [review]
Shouldn't the domain be gnmspecify.se instead of kulturutveckling.se (which does not exist)? Or is that part of the configuration to be made in each local installation (so that 'kulturutveckling.se' only acts as a placeholder)?

**Comment by mskyttner** [comment]
I searched for "kulturutveckling.se" using `grep -r kulturutveckling\.se` and couldn't find any hits... Where can this still be found? I wanted to get rid of it and have gnmspecify.se instead. Except for in the image names/slugs (but those do not mention "kulturutveckling.se". So if you found something somewhere, it should be replaced, I think.

**Comment by chrisIsen** [comment]
Ok, I must have looked at an old version of the docker-compose file. It is correct as I review it now.

**Pull request merged**
